### ISSUE TITLE
tdp-ui resolves localhost to IPv6 by defaults and errors out

### ISSUE THREAD

**Issue by gboutry** [TOSIT-IO/tdp-ui#10]
Tdp-ui firsts resolves `localhost:8000` to IPv6 and outputs errors, then it tries with IPv4 and succeeds.

We should favor IPv4 if possible not to output meaningless errors.

```
error - unhandledRejection: AxiosError: connect ECONNREFUSED ::1:8000
    at AxiosError.from (file:///~/projects/tdp-ui/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///~/projects/tdp-ui/node_modules/axios/lib/adapters/http.js:515:25)
    at RedirectableRequest.emit (node:events:527:28)
    at eventHandlers.<computed> (~/projects/tdp-ui/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketErrorListener (node:_http_client:454:9)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
```

**Comment by PaulFarault** [comment]
This shouldn't be a problem anymore as `axios` has been replaced by the native `fetch` API. Could you confirm @gboutry?

**Comment by gboutry** [comment]
I haven't seen this error message for a while now

**Comment by PaulFarault** [comment]
Good, thx!
